# This program takes two genome assemblies and quickly aligns them
#  and outputs the results into a format that can be easily uploaded
#  to D-genies.
#
# This program runs faster than running minimap2 on the whole genomes
#  because it splits the query into many smaller sequences.
#
# Queries are the sequences that will be split up and aligned
#  to the references.
queries:
  CoolAssem1:      /path/to/assembly/one.fasta
  AnotherAssembly: /path/to/assembly/two.fasta

references:
  refgenome1: /path/to/refegenome1/one.fasta
  refgenome2: /path/to/refgenome2/two.fasta