assemblies:
  assembly1: "/run/blobtools/on/this/assembly.fasta"

shotf: "/paired/WGS/reads/forward/file/here.fastq.gz"
shotr: "/paired/WGS/reads/reverse/file/here.fastq.gz"
# we use the diamond database to perform the searches
diamond_nr_db: "/path/to/nr.dmnd"
# we just use the nr blast database to extract the taxids for blobtools
nr_db: "/path/to/nr"
