# Author dts 2020
# dts@ucsc.edu
# dschultz@mbari.org
#
# This config file is for the script `config_GAP_hic_map5`
#  https://github.com/conchoecia/genome_assembly_pipelines
# To use this config file, copy it to the directory you
#  want to run the hi-c analysis in, then rename it to
#  config.yaml. Edit the config.yaml file and then run
#  snakemake --snakfile /path/to/genome_assembly_pipelines/scripts/GAP_hic_map

# The path to your assembly for which you want a Hi-C map goes here.
assemblies:
  code_name_for_this_assembly: "/path/to/assembly.fasta"

# This is the size of the bin for the Hi-C map.
#  I recommend a bin size of 25000 or 50000 for genomes over 1Gb
#  or a bin size of around 1000, 2000, or 5000bp for smaller genomes.
binsize:
  # The size of the bin goes here. Change this number to whatever
  #  based on the comment above.
  250000:
    # the zmin and zmax MUST be set to zero when running this pipeline.
    #  Halfway through, hicCorrectMatrix diagnostic_plot will run and
    #  generate png images of the z-scores of bin intensities.
    #  You must download these and determine the min and max z score
    #  for cutoff.
    #  Use this website as a guide https://hicexplorer.readthedocs.io/en/latest/content/example_usage.html#correction-of-hi-c-matrix
    #
    # Once you figure out what cutoffs you'd like, set zmin and zmax to
    #  something other than zero then just restart the pipeline
    zmin: 0
    zmax: 0
  # Yep - you can do multiple bin sizes
  50000:
    zmin: 0
    zmax: 0

# path to a file of transcripts, like an assembly from Trinity.
# Only use nucleotide sequences. Do not use protein fasta files.
# if you don't have any, kist comment out the whole thing
transcripts:
  - /path/to/transcripts.1.fa
  - /path/to/transcripts.2.fa

# Comment out the whole thing if you don't have long reads.
#  This is to get mapping depth across the genome.
LR:
  - /path/to/long/reads/file1.fq.gz
  - /path/to/long/reads/file2.fq.gz

# The are the paths to the Hi-C files. You can
#  have multiple fasta files per library.
#  It doesn't matter how you do it now, because
#  all of the libraries are concatenated together.
libs:
  HiC-lib1:
    read1:
    - /path/to/HiC-lib1_f.fastq.gz
    read2:
    - /path/to/HiC-lib1_r.fastq.gz
  Another-HiC-lib:
    read1:
    - /path/to/Another-HiC-lib_f.fastq.gz
    read2:
    - /path/to/Another-HiC-lib_r.fastq.gz
