# This is the example config file for GAP_annotate
#  - Annotates a single genome using a transcriptome,
#    long RNA-seq reads such as Iso-Seq,
#    protein sequences from closely related species,
#    and transcriptomes from closely related species

######### SOFTWARE PATHS ######################
# path to your stringtie executable
STRINGTIE: "/home/dschultz/git/stringtie-2.1.3b.Linux_x86_64/stringtie"
# path to your pinfish directory
PINFISHDIR: "/home/dschultz/git/pinfish"
# path to your STAR executable
STARPATH: /home/dschultz/git/STAR-2.7.1a/source/STAR
# path to prothint.py
PROTHINTPATH: /home/dschultz/git/ProtHint/bin/prothint.py
MAXRAM: 500
################################################


######### SAMPLE INFO ######################
# prefix to name the assembly as
PREFIX: "Eup01"
# annotation version to add to the filenames
VERSION: 1
# reference genome you want to annotate
REF: "/bigdata/user/darrin/euplokamis/assembly_steps/hirise_rename/GAP_reorder_assembly/output/assembly/euplo_hirise_output.fasta"
# transcriptome for the same sample/species you are annotating
TXOME: "/data/ncbi/newdb/db/CTE_Eupl_dunl_V3144-D2_TRI.fasta"
# long RNA-reads for the transcriptome you are annotating
LONGREADS: "/data/ncbi/newdb/db/CTE_Eupl_dunl_SRR777663_TRI.fasta"
# Illumina RNA-seq reads for the species you are annotating
RNAF: /data/assembly/_9704R-Utah/Fastq/9704X1_130221_SN141_0652_AC1T2YACXX_1_1.txt.gz
RNAR: /data/assembly/_9704R-Utah/Fastq/9704X1_130221_SN141_0652_AC1T2YACXX_1_2.txt.gz
##############################################

# these are proteins from closely related species
other_proteins:
 CTE_Aula_acum_D558-D10:     "/data/ncbi/newdb/db/CTE_Aula_acum_D558-D10_TRI.pep"
 CTE_Bath_chun_SRR10276160:  "/data/ncbi/newdb/db/CTE_Bath_chun_D423-D8_TRI.pep"
 CTE_Bath_fost_V3709-D5:     "/data/ncbi/newdb/db/CTE_Bath_fost_V3709-D5_TRI.pep"
 CTE_Bent_cten_T1074-SS1:    "/data/ncbi/newdb/db/CTE_Bent_cten_T1074-SS1_TRI.pep"
 CTE_Bero_abys_D340-SS3:     "/data/ncbi/newdb/db/CTE_Bero_abys_D340-SS3_TRI.pep"
 CTE_Bero_abys_SRR777787:    "/data/ncbi/newdb/db/CTE_Bero_abys_SRR777787_TRI.pep"
 CTE_Bero_cucu_D721-SS7:     "/data/ncbi/newdb/db/CTE_Bero_cucu_D721-SS7_TRI.pep"
 CTE_Beroe_sp_SRR5892577:    "/data/ncbi/newdb/db/CTE_Beroe_sp_SRR5892577_TRI.pep"
 CTE_Bero_fors_20111205:     "/data/ncbi/newdb/db/CTE_Bero_fors_20111205-BW3_TRI.pep"
 CTE_Bero_fors_SRR6074515:   "/data/ncbi/newdb/db/CTE_Bero_fors_SRR6074515_TRI.pep"
 CTE_Bero_ovat_KOK17-BW13:   "/data/ncbi/newdb/db/CTE_Bero_ovat_KOK17-BW13_TRI.pep"
 CTE_Bero_ovat_SRR6074516:   "/data/ncbi/newdb/db/CTE_Bero_ovat_SRR6074516_TRI.pep"
 CTE_B_forskalii_D785-D11:   "/data/ncbi/newdb/db/CTE_B_forskalii_D785-D11_TRI.pep"
 CTE_Boli_ashl_SRR5892570:   "/data/ncbi/newdb/db/CTE_Boli_ashl_SRR5892570_TRI.pep"
 CTE_Boli_infu_SRR6074521:   "/data/ncbi/newdb/db/CTE_Boli_infu_SRR6074521_TRI.pep"
 CTE_Boli_infu_SRR786491:    "/data/ncbi/newdb/db/CTE_Boli_infu_SRR786491_TRI.pep"
 CTE_Boli_infu_V3710-D1:     "/data/ncbi/newdb/db/CTE_Boli_infu_V3710-D1_TRI.pep"
 CTE_Boli_vitr_KM18BW2-4:    "/data/ncbi/newdb/db/CTE_Boli_vitr_KM18BW2-4_TRI.pep"
 CTE_Cest_vene_SEPT12-BW1:   "/data/ncbi/newdb/db/CTE_Cest_vene_SEPT12-BW1_TRI.pep"
 CTE_Char_fugi_T982-D6:      "/data/ncbi/newdb/db/CTE_Char_fugi_T982-D6_TRI.pep"
 CTE_Coel_aste_SRR786490:    "/data/ncbi/newdb/db/CTE_Coel_aste_SRR786490_TRI.pep"
 CTE_Coel_mete_SRR3407215:   "/data/ncbi/newdb/db/CTE_Coel_mete_SRR3407215_TRI.pep"
 CTE_Cten_clea_D422-D1:      "/data/ncbi/newdb/db/CTE_Cten_clea_D422-D1_TRI.pep"
 CTE_Ctenocero_sp_V2523-D2:  "/data/ncbi/newdb/db/CTE_Ctenocero_sp_V2523-D2_TRI.pep"
 CTE_Cydi_blac_D494-D3:      "/data/ncbi/newdb/db/CTE_Cydi_blac_D494-D3_TRI.pep"
 CTE_Cydi_gold_D779-D6:      "/data/ncbi/newdb/db/CTE_Cydi_gold_D779-D6_TRI.pep"
 CTE_Cydi_peac_D493-D1:      "/data/ncbi/newdb/db/CTE_Cydi_peac_D493-D1_TRI.pep"
 CTE_Cydi_redx_D497-D8:      "/data/ncbi/newdb/db/CTE_Cydi_redx_D497-D8_TRI.pep"
 CTE_Deio_kalo_D499-D11:     "/data/ncbi/newdb/db/CTE_Deio_kalo_D499-D11_TRI.pep"
 CTE_Dryo_glan_BWD-20020612: "/data/ncbi/newdb/db/CTE_Dryo_glan_BWD-20020612_TRI.pep"
 CTE_Dryo_glan_SRR777788:    "/data/ncbi/newdb/db/CTE_Dryo_glan_SRR777788_TRI.pep"
 CTE_Eupl_dunl_SRR777663:    "/data/ncbi/newdb/db/CTE_Eupl_dunl_SRR777663_TRI.pep"
 CTE_Eupl_dunl_V3144-D2:     "/data/ncbi/newdb/db/CTE_Eupl_dunl_V3144-D2_TRI.pep"
 CTE_Eurh_vexi_KMBW1-16:     "/data/ncbi/newdb/db/CTE_Eurh_vexi_KMBW1-16_TRI.pep"
 CTE_Eurh_vexi_SRR6074510:   "/data/ncbi/newdb/db/CTE_Eurh_vexi_SRR6074510_TRI.pep"
 CTE_Haec_beeh_20131119-BW1: "/data/ncbi/newdb/db/CTE_Haec_beeh_20131119-BW1_TRI.pep"
 CTE_Haec_rubr_V3709-D2:     "/data/ncbi/newdb/db/CTE_Haec_rubr_V3709-D2_TRI.pep"
 CTE_Horm_cali_D914-T1:      "/data/ncbi/newdb/db/CTE_Horm_cali_D914-T1_TRI.pep"
 CTE_Horm_palm_SRR6074513:   "/data/ncbi/newdb/db/CTE_Horm_palm_SRR6074513_TRI.pep"
 CTE_Horm_sp_SRR1992642:     "/data/ncbi/newdb/db/CTE_Horm_sp_SRR1992642_TRI.pep"
 CTE_Kiyo_usag_D558-D3:      "/data/ncbi/newdb/db/CTE_Kiyo_usag_D558-D3_TRI.pep"
 CTE_Lamp_crue_D421-D2:      "/data/ncbi/newdb/db/CTE_Lamp_crue_D421-D2_TRI.pep"
 CTE_Lamp_lact_200609BW:     "/data/ncbi/newdb/db/CTE_Lamp_lact_200609BW_TRI.pep"
 CTE_Lamp_lact_26MAR19:      "/data/ncbi/newdb/db/CTE_Lamp_lact_26MAR19_TRI.pep"
 CTE_Lamp_panc_D498-SS7:     "/data/ncbi/newdb/db/CTE_Lamp_panc_D498-SS7_TRI.pep"
 CTE_Lamp_panc_SRR3407163:   "/data/ncbi/newdb/db/CTE_Lamp_panc_SRR3407163_TRI.pep"
 CTE_Lamp_sp_SRR9162937:     "/data/ncbi/newdb/db/CTE_Lamp_sp_SRR9162937_TRI.pep"
 CTE_Leuc_pulc_V3762-D6:     "/data/ncbi/newdb/db/CTE_Leuc_pulc_V3762-D6_TRI.pep"
 CTE_Llyr_bent_D557-D5:      "/data/ncbi/newdb/db/CTE_Llyr_bent_D557-D5_TRI.pep"
 CTE_Llyr_copp_D493-D6:      "/data/ncbi/newdb/db/CTE_Llyr_copp_D493-D6_TRI.pep"
 CTE_Llyria_sp_D1019-D3:     "/data/ncbi/newdb/db/CTE_Llyria_sp_D1019-D3_TRI.pep"
 CTE_Mert_ovum_Sval:         "/data/ncbi/newdb/db/CTE_Mert_ovum_Sval_TRI.pep"
 CTE_Mert_sp_SRR786492:      "/data/ncbi/newdb/db/CTE_Mert_sp_SRR786492_TRI.pep"
 CTE_Mnem_leid_ERR2752243:   "/data/ncbi/newdb/db/CTE_Mnem_leid_ERR2752243_TRI.pep"
 CTE_Mnem_leid_ERR2752250:   "/data/ncbi/newdb/db/CTE_Mnem_leid_ERR2752250_TRI.pep"
 CTE_Mnem_leid_SRR6074509:   "/data/ncbi/newdb/db/CTE_Mnem_leid_SRR6074509_TRI.pep"
 CTE_Neph_red_V3710-D3:      "/data/ncbi/newdb/db/CTE_Neph_red_V3710-D3_TRI.pep"
 CTE_Neph_red_V3710-D8:      "/data/ncbi/newdb/db/CTE_Neph_red_V3710-D8_TRI.pep"
 CTE_Neph_whit_T841-D5:      "/data/ncbi/newdb/db/CTE_Neph_whit_T841-D5_TRI.pep"
 CTE_Ocyr_crys_BW04-GoC:     "/data/ncbi/newdb/db/CTE_Ocyr_crys_BW04-GoC_TRI.pep"
 CTE_Ocyr_crys_SRR6074507:   "/data/ncbi/newdb/db/CTE_Ocyr_crys_SRR6074507_TRI.pep"
 CTE_Ocyr_crys_SRR6074508:   "/data/ncbi/newdb/db/CTE_Ocyr_crys_SRR6074508_TRI.pep"
 CTE_Ocyr_macu_BWD-20060929: "/data/ncbi/newdb/db/CTE_Ocyr_macu_BWD-20060929_TRI.pep"
 CTE_Pleu_bach_20190417:     "/data/ncbi/newdb/db/CTE_Pleu_bach_20190417_TRI.pep"
 CTE_Pleu_pile_SRR789901:    "/data/ncbi/newdb/db/CTE_Pleu_pile_SRR789901_TRI.pep"
 CTE_Pleu_sp_SRR5892573:     "/data/ncbi/newdb/db/CTE_Pleu_sp_SRR5892573_TRI.pep"
 CTE_Pleu_sp_SRR6074517:     "/data/ncbi/newdb/db/CTE_Pleu_sp_SRR6074517_TRI.pep"
 CTE_Puki_falc_SRR5892572:   "/data/ncbi/newdb/db/CTE_Puki_falc_SRR5892572_TRI.pep"
 CTE_Tetr_angu_V3629-D5:     "/data/ncbi/newdb/db/CTE_Tetr_angu_V3629-D5_TRI.pep"
 CTE_Thal_inco_V3560-D2:     "/data/ncbi/newdb/db/CTE_Thal_inco_V3560-D2_TRI.pep"
 CTE_Tjal_sp_D961-SS2:       "/data/ncbi/newdb/db/CTE_Tjal_sp_D961-SS2_TRI.pep"
 CTE_Vall_mult_SRR3407164:   "/data/ncbi/newdb/db/CTE_Vall_mult_SRR3407164_TRI.pep"
 CTE_Vall_mult_SRR786489:    "/data/ncbi/newdb/db/CTE_Vall_mult_SRR786489_TRI.pep"
 CTE_Vamp_delm_SRR9162936:   "/data/ncbi/newdb/db/CTE_Vamp_delm_SRR9162936_TRI.pep"
 CTE_Vela_para_SEPT12-BW3:   "/data/ncbi/newdb/db/CTE_Vela_para_SEPT12-BW3_TRI.pep"
 CTE_Verm_loba_D326-SS6:     "/data/ncbi/newdb/db/CTE_Verm_loba_D326-SS6_TRI.pep"
 CTE_Weir_cten_V2848-D2:     "/data/ncbi/newdb/db/CTE_Weir_cten_V2848-D2_TRI.pep"

# these are transcriptomes from closely related species
other_transcriptomes:
  CTE_Aula_acum_D558-D10: "/bigdata/make_txomes/txomes/final/CTE_Aula_acum_D558-D10_TRI.fasta"
  CTE_Bath_chun_D423-D8: "/bigdata/make_txomes/txomes/final/CTE_Bath_chun_D423-D8_TRI.fasta"
  CTE_Bath_chun_SRR10276160: "/bigdata/make_txomes/txomes/final/CTE_Bath_chun_SRR10276160_TRI.fasta"
  CTE_Bath_fost_V3709-D5: "/bigdata/make_txomes/txomes/final/CTE_Bath_fost_V3709-D5_TRI.fasta"
  CTE_Bent_cten_T1074-SS1: "/bigdata/make_txomes/txomes/final/CTE_Bent_cten_T1074-SS1_TRI.fasta"
  CTE_Bero_abys_D340-SS3: "/bigdata/make_txomes/txomes/final/CTE_Bero_abys_D340-SS3_TRI.fasta"
  CTE_Bero_abys_SRR777787: "/bigdata/make_txomes/txomes/final/CTE_Bero_abys_SRR777787_TRI.fasta"
  CTE_Bero_cucu_D721-SS7: "/bigdata/make_txomes/txomes/final/CTE_Bero_cucu_D721-SS7_TRI.fasta"
  CTE_Beroe_sp_SRR5892577: "/bigdata/make_txomes/txomes/final/CTE_Beroe_sp_SRR5892577_TRI.fasta"
  CTE_Bero_fors_20111205: "/bigdata/make_txomes/txomes/final/CTE_Bero_fors_20111205-BW3_TRI.fasta"
  CTE_Bero_fors_SRR6074515: "/bigdata/make_txomes/txomes/final/CTE_Bero_fors_SRR6074515_TRI.fasta"
  CTE_Bero_ovat_KOK17-BW13: "/bigdata/make_txomes/txomes/final/CTE_Bero_ovat_KOK17-BW13_TRI.fasta"
  CTE_Bero_ovat_SRR6074516: "/bigdata/make_txomes/txomes/final/CTE_Bero_ovat_SRR6074516_TRI.fasta"
  CTE_B_forskalii_D785-D11: "/bigdata/make_txomes/txomes/final/CTE_B_forskalii_D785-D11_TRI.fasta"
  CTE_Boli_ashl_SRR5892570: "/bigdata/make_txomes/txomes/final/CTE_Boli_ashl_SRR5892570_TRI.fasta"
  CTE_Boli_infu_SRR6074521: "/bigdata/make_txomes/txomes/final/CTE_Boli_infu_SRR6074521_TRI.fasta"
  CTE_Boli_infu_SRR786491: "/bigdata/make_txomes/txomes/final/CTE_Boli_infu_SRR786491_TRI.fasta"
  CTE_Boli_infu_V3710-D1: "/bigdata/make_txomes/txomes/final/CTE_Boli_infu_V3710-D1_TRI.fasta"
  CTE_Boli_vitr_KM18BW2-4: "/bigdata/make_txomes/txomes/final/CTE_Boli_vitr_KM18BW2-4_TRI.fasta"
  CTE_Cest_vene_SEPT12-BW1: "/bigdata/make_txomes/txomes/final/CTE_Cest_vene_SEPT12-BW1_TRI.fasta"
  CTE_Char_fugi_T982-D6: "/bigdata/make_txomes/txomes/final/CTE_Char_fugi_T982-D6_TRI.fasta"
  CTE_Coel_aste_SRR786490: "/bigdata/make_txomes/txomes/final/CTE_Coel_aste_SRR786490_TRI.fasta"
  CTE_Coel_mete_SRR3407215: "/bigdata/make_txomes/txomes/final/CTE_Coel_mete_SRR3407215_TRI.fasta"
  CTE_Cten_clea_D422-D1: "/bigdata/make_txomes/txomes/final/CTE_Cten_clea_D422-D1_TRI.fasta"
  CTE_Ctenocero_sp_V2523-D2: "/bigdata/make_txomes/txomes/final/CTE_Ctenocero_sp_V2523-D2_TRI.fasta"
  CTE_Cydi_blac_D494-D3: "/bigdata/make_txomes/txomes/final/CTE_Cydi_blac_D494-D3_TRI.fasta"
  CTE_Cydi_gold_D779-D6: "/bigdata/make_txomes/txomes/final/CTE_Cydi_gold_D779-D6_TRI.fasta"
  CTE_Cydi_peac_D493-D1: "/bigdata/make_txomes/txomes/final/CTE_Cydi_peac_D493-D1_TRI.fasta"
  CTE_Cydi_redx_D497-D8: "/bigdata/make_txomes/txomes/final/CTE_Cydi_redx_D497-D8_TRI.fasta"
  CTE_Deio_kalo_D499-D11: "/bigdata/make_txomes/txomes/final/CTE_Deio_kalo_D499-D11_TRI.fasta"
  CTE_Dryo_glan_BWD-20020612: "/bigdata/make_txomes/txomes/final/CTE_Dryo_glan_BWD-20020612_TRI.fasta"
  CTE_Dryo_glan_SRR777788: "/bigdata/make_txomes/txomes/final/CTE_Dryo_glan_SRR777788_TRI.fasta"
  CTE_Eupl_dunl_SRR777663: "/bigdata/make_txomes/txomes/final/CTE_Eupl_dunl_SRR777663_TRI.fasta"
  CTE_Eupl_dunl_V3144-D2: "/bigdata/make_txomes/txomes/final/CTE_Eupl_dunl_V3144-D2_TRI.fasta"
  CTE_Eurh_vexi_KMBW1-16: "/bigdata/make_txomes/txomes/final/CTE_Eurh_vexi_KMBW1-16_TRI.fasta"
  CTE_Eurh_vexi_SRR6074510: "/bigdata/make_txomes/txomes/final/CTE_Eurh_vexi_SRR6074510_TRI.fasta"
  CTE_Haec_beeh_20131119-BW: "/bigdata/make_txomes/txomes/final/CTE_Haec_beeh_20131119-BW1_TRI.fasta"
  CTE_Haec_rubr_V3709-D2: "/bigdata/make_txomes/txomes/final/CTE_Haec_rubr_V3709-D2_TRI.fasta"
  CTE_Horm_cali_D914-T1: "/bigdata/make_txomes/txomes/final/CTE_Horm_cali_D914-T1_TRI.fasta"
  CTE_Horm_palm_SRR6074513: "/bigdata/make_txomes/txomes/final/CTE_Horm_palm_SRR6074513_TRI.fasta"
  CTE_Horm_sp_SRR1992642: "/bigdata/make_txomes/txomes/final/CTE_Horm_sp_SRR1992642_TRI.fasta"
  CTE_Kiyo_usag_D558-D3: "/bigdata/make_txomes/txomes/final/CTE_Kiyo_usag_D558-D3_TRI.fasta"
  CTE_Lamp_crue_D421-D2: "/bigdata/make_txomes/txomes/final/CTE_Lamp_crue_D421-D2_TRI.fasta"
  CTE_Lamp_lact_200609BW: "/bigdata/make_txomes/txomes/final/CTE_Lamp_lact_200609BW_TRI.fasta"
  CTE_Lamp_lact_26MAR19: "/bigdata/make_txomes/txomes/final/CTE_Lamp_lact_26MAR19_TRI.fasta"
  CTE_Lamp_panc_D498-SS7: "/bigdata/make_txomes/txomes/final/CTE_Lamp_panc_D498-SS7_TRI.fasta"
  CTE_Lamp_panc_SRR3407163: "/bigdata/make_txomes/txomes/final/CTE_Lamp_panc_SRR3407163_TRI.fasta"
  CTE_Lamp_sp_SRR9162937: "/bigdata/make_txomes/txomes/final/CTE_Lamp_sp_SRR9162937_TRI.fasta"
  CTE_Leuc_pulc_V3762-D6: "/bigdata/make_txomes/txomes/final/CTE_Leuc_pulc_V3762-D6_TRI.fasta"
  CTE_Llyr_bent_D557-D5: "/bigdata/make_txomes/txomes/final/CTE_Llyr_bent_D557-D5_TRI.fasta"
  CTE_Llyr_copp_D493-D6: "/bigdata/make_txomes/txomes/final/CTE_Llyr_copp_D493-D6_TRI.fasta"
  CTE_Llyria_sp_D1019-D3: "/bigdata/make_txomes/txomes/final/CTE_Llyria_sp_D1019-D3_TRI.fasta"
  CTE_Mert_ovum_Sval: "/bigdata/make_txomes/txomes/final/CTE_Mert_ovum_Sval_TRI.fasta"
  CTE_Mert_sp_SRR786492: "/bigdata/make_txomes/txomes/final/CTE_Mert_sp_SRR786492_TRI.fasta"
  CTE_Mnem_leid_ERR2752243: "/bigdata/make_txomes/txomes/final/CTE_Mnem_leid_ERR2752243_TRI.fasta"
  CTE_Mnem_leid_ERR2752250: "/bigdata/make_txomes/txomes/final/CTE_Mnem_leid_ERR2752250_TRI.fasta"
  CTE_Mnem_leid_SRR6074509: "/bigdata/make_txomes/txomes/final/CTE_Mnem_leid_SRR6074509_TRI.fasta"
  CTE_Neph_red_V3710-D3: "/bigdata/make_txomes/txomes/final/CTE_Neph_red_V3710-D3_TRI.fasta"
  CTE_Neph_red_V3710-D8: "/bigdata/make_txomes/txomes/final/CTE_Neph_red_V3710-D8_TRI.fasta"
  CTE_Neph_whit_T841-D5: "/bigdata/make_txomes/txomes/final/CTE_Neph_whit_T841-D5_TRI.fasta"
  CTE_Ocyr_crys_BW04-GoC: "/bigdata/make_txomes/txomes/final/CTE_Ocyr_crys_BW04-GoC_TRI.fasta"
  CTE_Ocyr_crys_SRR6074507: "/bigdata/make_txomes/txomes/final/CTE_Ocyr_crys_SRR6074507_TRI.fasta"
  CTE_Ocyr_crys_SRR6074508: "/bigdata/make_txomes/txomes/final/CTE_Ocyr_crys_SRR6074508_TRI.fasta"
  CTE_Ocyr_macu_BWD-20060929: "/bigdata/make_txomes/txomes/final/CTE_Ocyr_macu_BWD-20060929_TRI.fasta"
  CTE_Pleu_bach_20190417: "/bigdata/make_txomes/txomes/final/CTE_Pleu_bach_20190417_TRI.fasta"
  CTE_Pleu_pile_SRR789901: "/bigdata/make_txomes/txomes/final/CTE_Pleu_pile_SRR789901_TRI.fasta"
  CTE_Pleu_sp_SRR5892573: "/bigdata/make_txomes/txomes/final/CTE_Pleu_sp_SRR5892573_TRI.fasta"
  CTE_Pleu_sp_SRR6074517: "/bigdata/make_txomes/txomes/final/CTE_Pleu_sp_SRR6074517_TRI.fasta"
  CTE_Puki_falc_SRR5892572: "/bigdata/make_txomes/txomes/final/CTE_Puki_falc_SRR5892572_TRI.fasta"
  CTE_Tetr_angu_V3629-D5: "/bigdata/make_txomes/txomes/final/CTE_Tetr_angu_V3629-D5_TRI.fasta"
  CTE_Thal_inco_V3560-D2: "/bigdata/make_txomes/txomes/final/CTE_Thal_inco_V3560-D2_TRI.fasta"
  CTE_Tjal_sp_D961-SS2: "/bigdata/make_txomes/txomes/final/CTE_Tjal_sp_D961-SS2_TRI.fasta"
  CTE_Vall_mult_SRR3407164: "/bigdata/make_txomes/txomes/final/CTE_Vall_mult_SRR3407164_TRI.fasta"
  CTE_Vall_mult_SRR786489: "/bigdata/make_txomes/txomes/final/CTE_Vall_mult_SRR786489_TRI.fasta"
  CTE_Vamp_delm_SRR9162936: "/bigdata/make_txomes/txomes/final/CTE_Vamp_delm_SRR9162936_TRI.fasta"
  CTE_Vela_para_SEPT12-BW3: "/bigdata/make_txomes/txomes/final/CTE_Vela_para_SEPT12-BW3_TRI.fasta"
  CTE_Verm_loba_D326-SS6: "/bigdata/make_txomes/txomes/final/CTE_Verm_loba_D326-SS6_TRI.fasta"
  CTE_Weir_cten_V2848-D2: "/bigdata/make_txomes/txomes/final/CTE_Weir_cten_V2848-D2_TRI.fasta"
