# Description: This is the template config.yaml file for the GAP script, GAP_yahs
# Author: Darrin T. Schultz https://github.com/conchoecia
# Date:   July 2023
# 
# Copy this example config file to your local directory, rename it as config.yaml.
# Then, add your genome assembly information. Do not use underscores in the assembly name.
# Run the program with snakemake --snakefile /your/path/to/genome_assembly_pipelines/snakefiles/GAP_yahs
#  
# This pipeline scaffolds genome assemblies using proximity ligation data.
#  The pipeline then makes an editable .hic file.



assemblies:
  assembly1: "/path/to/assembly1/to/scaffold.fasta"
  some_other_assem: "/this/path/is/to/the/second/assembly/we/want/to/scaffold.fasta"

# The libraries can be either Chicago or Hi-C. Only run one type at a time.
libs:
  ChicagoLib1:
    read1: "/path/to/ChicagoLib1_f.fastq.gz"
    read2: "/path/to/ChicagoLib1_r.fastq.gz"
  Hi-C_Lib1:
    read1: "/path/to/the/other/AwesomeHi-CLib_R1.fastq.gz"
    read2: "/path/to/the/other/AwesomeHi-CLib_R2.fastq.gz"
  MoreHi-C:
    read1: "/path/to/the/other/MoreHiC_R1.fastq.gz"
    read2: "/path/to/the/other/MoreHiC_R2.fastq.gz"

