assemblies:
  assembly1: "/run/blobtools/on/this/assembly.fasta"

shotf: "/paired/WGS/reads/forward/file/here.fastq.gz"
shotr: "/paired/WGS/reads/reverse/file/here.fastq.gz"
diamond_db: "/path/to/uniprot_ref_proteomes.diamond.dmnd"
