assemblies:
  assembly1: "/path/to/assembly1/to/scaffold.fasta"
  some_other_assem: "/this/path/is/to/the/second/assembly/we/want/to/scaffold.fasta"

# The libraries can be either Chicago or Hi-C. Only run one type at a time.
libs:
  ChicagoLib1:
    read1: "/path/to/ChicagoLib1_f.fastq.gz"
    read2: "/path/to/ChicagoLib1_r.fastq.gz"
  Hi-C_Lib1:
    read1: "/path/to/the/other/AwesomeHi-CLib_R1.fastq.gz"
    read2: "/path/to/the/other/AwesomeHi-CLib_R2.fastq.gz"
  MoreHi-C:
    read1: "/path/to/the/other/MoreHiC_R1.fastq.gz"
    read2: "/path/to/the/other/MoreHiC_R2.fastq.gz"

